### ISSUE TITLE
cnxb.github.io不可访问

### ISSUE THREAD

**Issue by hurui200320** [cnxb/cnxb.github.io#1]
你好，我是[天空Blond](https://skyblond.info)的博主，最近发现友链不能访问了，遂进行检查，确定不是我的网络问题。

看Github Repo的CNAME似乎是换成了新的域名。所以需要我把我这边的友链换成[新域名](https://ijk.ink/)嘛？

**Comment by cnxb** [comment]
嗯...是的
现在换了域名..
应该就是CNAME里面那个域名

**Comment by cnxb** [comment]
因为现在也不怎么更新了...如果不方便的话删掉也可以..

**Comment by hurui200320** [comment]
没关系，我已经修改过来啦
